// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObeSystem.Repository;

namespace ObeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210117044034_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ObeSystem.Models.Lolist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lo_code")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lo_name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Lolists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Study about 12 patterns",
                            Lo_code = "LO1",
                            Lo_name = "Patterns",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 2,
                            Description = "Study about architecture",
                            Lo_code = "LO2",
                            Lo_name = "Architecture",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = "Efficiency code writing",
                            Lo_code = "LO3",
                            Lo_name = "Clean-Code",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "Final Project",
                            Lo_code = "LO4",
                            Lo_name = "Implementation",
                            Weight = 0.20000000000000001
                        });
                });

            modelBuilder.Entity("ObeSystem.Models.Polist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("LolistId")
                        .HasColumnType("int");

                    b.Property<string>("Po_code")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Po_name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LolistId");

                    b.ToTable("Polists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Creating Resume",
                            Po_code = "PO1",
                            Po_name = "Assignement1",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Project-Proposal",
                            Po_code = "PO2",
                            Po_name = "Project-Imp",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mid-Evaluation",
                            Po_code = "PO3",
                            Po_name = "Project-Viva",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 4,
                            Description = "End-Semester",
                            Po_code = "PO4",
                            Po_name = "Final-Evaluation",
                            Weight = 0.5
                        });
                });

            modelBuilder.Entity("ObeSystem.Models.Polist", b =>
                {
                    b.HasOne("ObeSystem.Models.Lolist", null)
                        .WithMany("Polists")
                        .HasForeignKey("LolistId");
                });

            modelBuilder.Entity("ObeSystem.Models.Lolist", b =>
                {
                    b.Navigation("Polists");
                });
#pragma warning restore 612, 618
        }
    }
}
