// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObeSystem.Repository;

namespace ObeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ObeSystem.Models.Lolist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lo_code")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Lo_name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Lolists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nothing",
                            Lo_code = "LO1",
                            Lo_name = "Practical",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nothing",
                            Lo_code = "LO1",
                            Lo_name = "Practical",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nothing",
                            Lo_code = "LO1",
                            Lo_name = "Practical",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nothing",
                            Lo_code = "LO1",
                            Lo_name = "Practical",
                            Weight = 0.20000000000000001
                        });
                });

            modelBuilder.Entity("ObeSystem.Models.Polist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("LolistId")
                        .HasColumnType("int");

                    b.Property<string>("Po_code")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Po_name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LolistId");

                    b.ToTable("Polists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nothing",
                            Po_code = "PO1",
                            Po_name = "Viva",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nothing",
                            Po_code = "PO1",
                            Po_name = "Viva",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nothing",
                            Po_code = "PO1",
                            Po_name = "Viva",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nothing",
                            Po_code = "PO1",
                            Po_name = "Viva",
                            Weight = 0.5
                        });
                });

            modelBuilder.Entity("ObeSystem.Models.Polist", b =>
                {
                    b.HasOne("ObeSystem.Models.Lolist", "Lolist")
                        .WithMany("Polists")
                        .HasForeignKey("LolistId");

                    b.Navigation("Lolist");
                });

            modelBuilder.Entity("ObeSystem.Models.Lolist", b =>
                {
                    b.Navigation("Polists");
                });
#pragma warning restore 612, 618
        }
    }
}
